"""created UserOauthServices

Revision ID: 34620e8a36a7
Revises: 2677dae41b41
Create Date: 2022-07-06 18:49:15.075107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34620e8a36a7'
down_revision = '2677dae41b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_oauth_services',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=150), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=150), nullable=True),
    sa.Column('access_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_oauth_services')
    # ### end Alembic commands ###
